// Sample data for the Lamhelle prototype.
// These are fictional placeholder businesses used to demo the map and
// recommendation views for South Dublin. Swap this array for a real feed
// (API or CMS) before launch.

const CATEGORIES = [
  "Cafe",
  "Boutique Clothing",
  "Florist",
  "Homeware",
  "Gift Shop",
  "Bakery",
  "Bookshop",
  "Baby & Kids",
  "Specialist Service",
  "Deli",
];

const BUSINESSES = [
  {
    id: "b1",
    name: "The Ranelagh Roastery",
    category: "Cafe",
    area: "Ranelagh",
    address: "14 Ranelagh Village, Dublin 6",
    lat: 53.3252,
    lng: -6.2540,
    blurb: "Small-batch coffee roasted on site, with a daily-changing bake selection.",
    tags: ["coffee", "brunch", "pastries"],
    priceLevel: 2,
    featured: true,
  },
  {
    id: "b2",
    name: "Dundrum Bloom & Stem",
    category: "Florist",
    area: "Dundrum",
    address: "3 Main Street, Dundrum, Dublin 14",
    lat: 53.2905,
    lng: -6.2450,
    blurb: "Family-run florist specialising in seasonal Irish-grown flowers and wedding work.",
    tags: ["flowers", "gifts", "weddings"],
    priceLevel: 2,
    featured: true,
  },
  {
    id: "b3",
    name: "Sandymount Wool & Weave",
    category: "Homeware",
    area: "Sandymount",
    address: "22 Sandymount Green, Dublin 4",
    lat: 53.3323,
    lng: -6.2168,
    blurb: "Irish linen, knitwear throws and handmade ceramics for the home.",
    tags: ["homeware", "irish-made", "gifts"],
    priceLevel: 3,
    featured: false,
  },
  {
    id: "b4",
    name: "Rathmines Rare Books",
    category: "Bookshop",
    area: "Rathmines",
    address: "56 Rathmines Road Lower, Dublin 6",
    lat: 53.3231,
    lng: -6.2653,
    blurb: "New and second-hand books with a strong Irish-interest and poetry section.",
    tags: ["books", "gifts", "quiet-browse"],
    priceLevel: 1,
    featured: false,
  },
  {
    id: "b5",
    name: "Little Acorns Baby Co.",
    category: "Baby & Kids",
    area: "Terenure",
    address: "8 Terenure Village, Dublin 6W",
    lat: 53.3013,
    lng: -6.2887,
    blurb: "Baby gifts, hampers and Irish-made knitwear for newborns.",
    tags: ["baby-gift", "newborn", "hampers"],
    priceLevel: 2,
    featured: true,
  },
  {
    id: "b6",
    name: "Blackrock Boutique",
    category: "Boutique Clothing",
    area: "Blackrock",
    address: "11 Main Street, Blackrock, Co. Dublin",
    lat: 53.3020,
    lng: -6.1780,
    blurb: "Curated women's fashion from independent Irish and European designers.",
    tags: ["fashion", "occasion-wear", "accessories"],
    priceLevel: 3,
    featured: false,
  },
  {
    id: "b7",
    name: "Dun Laoghaire Deli & Provisions",
    category: "Deli",
    area: "Dun Laoghaire",
    address: "45 George's Street Upper, Dun Laoghaire",
    lat: 53.2938,
    lng: -6.1319,
    blurb: "Irish farmhouse cheeses, cured meats and picnic hampers by the harbour.",
    tags: ["cheese", "picnic", "local-produce"],
    priceLevel: 2,
    featured: true,
  },
  {
    id: "b8",
    name: "Dalkey Craft & Gift",
    category: "Gift Shop",
    area: "Dalkey",
    address: "2 Castle Street, Dalkey, Co. Dublin",
    lat: 53.2773,
    lng: -6.1030,
    blurb: "Handmade pottery, jewellery and cards from Irish makers.",
    tags: ["gifts", "handmade", "jewellery"],
    priceLevel: 2,
    featured: false,
  },
  {
    id: "b9",
    name: "Rathgar Bakehouse",
    category: "Bakery",
    area: "Rathgar",
    address: "19 Rathgar Road, Dublin 6",
    lat: 53.3138,
    lng: -6.2686,
    blurb: "Sourdough, viennoiserie and celebration cakes baked fresh every morning.",
    tags: ["bakery", "sourdough", "celebration-cakes"],
    priceLevel: 1,
    featured: true,
  },
  {
    id: "b10",
    name: "Stillorgan Stitch & Mend",
    category: "Specialist Service",
    area: "Stillorgan",
    address: "Stillorgan Shopping Centre, Co. Dublin",
    lat: 53.2789,
    lng: -6.2050,
    blurb: "Alterations, tailoring and bespoke fittings for every occasion.",
    tags: ["tailoring", "alterations", "occasion-wear"],
    priceLevel: 2,
    featured: false,
  },
  {
    id: "b11",
    name: "Donnybrook Home Studio",
    category: "Homeware",
    area: "Donnybrook",
    address: "5 Donnybrook Road, Dublin 4",
    lat: 53.3225,
    lng: -6.2312,
    blurb: "Irish-designed lighting, cushions and small furniture pieces.",
    tags: ["homeware", "irish-made", "interiors"],
    priceLevel: 3,
    featured: false,
  },
  {
    id: "b12",
    name: "Ballsbridge Petal Co.",
    category: "Florist",
    area: "Ballsbridge",
    address: "60 Merrion Road, Ballsbridge, Dublin 4",
    lat: 53.3298,
    lng: -6.2276,
    blurb: "Contemporary bouquets and same-day local delivery across South Dublin.",
    tags: ["flowers", "same-day-delivery", "gifts"],
    priceLevel: 2,
    featured: true,
  },
  {
    id: "b13",
    name: "Terenure Coffee Room",
    category: "Cafe",
    area: "Terenure",
    address: "34 Terenure Road East, Dublin 6W",
    lat: 53.3013,
    lng: -6.2887,
    blurb: "Neighbourhood cafe known for its all-day brunch and traybakes.",
    tags: ["coffee", "brunch", "traybakes"],
    priceLevel: 2,
    featured: false,
  },
  {
    id: "b14",
    name: "Dundrum Bookworm",
    category: "Bookshop",
    area: "Dundrum",
    address: "17 Main Street, Dundrum, Dublin 14",
    lat: 53.2905,
    lng: -6.2450,
    blurb: "Children's books, book clubs and an in-store storytime every Saturday.",
    tags: ["books", "kids", "storytime"],
    priceLevel: 1,
    featured: false,
  },
  {
    id: "b15",
    name: "Sandymount Style Edit",
    category: "Boutique Clothing",
    area: "Sandymount",
    address: "9 Sandymount Green, Dublin 4",
    lat: 53.3323,
    lng: -6.2168,
    blurb: "Everyday womenswear from Irish designers, sized inclusively.",
    tags: ["fashion", "irish-designers", "everyday-wear"],
    priceLevel: 2,
    featured: true,
  },
  {
    id: "b16",
    name: "Rathmines Green Grocer",
    category: "Deli",
    area: "Rathmines",
    address: "12 Rathmines Road Upper, Dublin 6",
    lat: 53.3231,
    lng: -6.2653,
    blurb: "Fresh local produce, deli counter and ready-made meals.",
    tags: ["local-produce", "deli", "ready-meals"],
    priceLevel: 1,
    featured: false,
  },
  {
    id: "b17",
    name: "Blackrock Framing & Gifts",
    category: "Specialist Service",
    area: "Blackrock",
    address: "27 Main Street, Blackrock, Co. Dublin",
    lat: 53.3020,
    lng: -6.1780,
    blurb: "Custom picture framing alongside a small curated gift corner.",
    tags: ["framing", "gifts", "custom-work"],
    priceLevel: 2,
    featured: false,
  },
  {
    id: "b18",
    name: "Dalkey Little Ones",
    category: "Baby & Kids",
    area: "Dalkey",
    address: "14 Railway Road, Dalkey, Co. Dublin",
    lat: 53.2773,
    lng: -6.1030,
    blurb: "Baby clothing, toys and christening gifts made in Ireland.",
    tags: ["baby-gift", "toys", "christening"],
    priceLevel: 2,
    featured: false,
  },
];
